version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/.rundoc-workspace"
    schedule:
      interval: "monthly"
    groups:
      ruby-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"
