name: failure_free_docs
on:
  pull_request:
    paths:
      - "docs/fail/**"

permissions:
  contents: read

jobs:
  checks_docs_for_failures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Check PR for failures
        run: |
          FAILING=$(find ./docs/fail -type f)
          if [ -z "$FAILING" ]; then
            echo "No failing docs found"
          else
            echo "ERROR:"
            echo "Failing docs found. Delete the files and retry generation."
            echo "If the failure persists, notify the language owner"
            echo
            echo "$FAILING"
            exit 1
          fi
