name: failure_free_docs
on:
  pull_request:
    paths:
      - "docs/fail/**"

permissions:
  contents: read

jobs:
  checks-docs-for-failures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check PR for failures
        run: |
          if [[ -e ./docs/fail ]]; then
            echo "No failing docs found"
          else
            echo "ERROR: Failing docs found in the ./docs/fail/ directory!"
            echo "Try retriggering the rundoc job to see if the failures are intermittent."
            echo "If the failure persists, notify the language owner."
            exit 1
          fi
